services:
  challenge:
    build:
      context: ${CTF_SOURCES_ROOT}/google-ctf/2023/quals/crypto-mytls/challenge
      dockerfile: Dockerfile
    ports:
      - "18102:1337"
    restart: unless-stopped

